#include "mock_windows.h"
#include <wchar.h>
#include <wctype.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>

#include "../parser.h"

// The logic will be included from postprocess_logic.c which is generated by Makefile
#include "postprocess_logic.c"

void test_parse_postprocessing_line() {
    printf("Running ParsePostProcessingLine tests...\n");

    EnhancedProgressInfo progress;
    InitializeEnhancedProgressInfo(&progress);

    // Test case 1: NULL inputs
    assert(ParsePostProcessingLine(NULL, &progress) == FALSE);
    assert(ParsePostProcessingLine(L"test", NULL) == FALSE);

    // Test case 2: [ffmpeg] line
    ParsePostProcessingLine(L"[ffmpeg] Post-processing", &progress);
    assert(progress.currentOperation != NULL);
    assert(wcscmp(progress.currentOperation, L"Converting video format") == 0);

    // Test case 3: Merging formats
    ParsePostProcessingLine(L"Merging formats into mp4", &progress);
    assert(wcscmp(progress.currentOperation, L"Merging video and audio") == 0);

    // Test case 4: Correcting container
    ParsePostProcessingLine(L"Correcting container in video.mp4", &progress);
    assert(wcscmp(progress.currentOperation, L"Correcting video container") == 0);

    // Test case 5: Generic post-processing
    ParsePostProcessingLine(L"Some other post-process", &progress);
    assert(wcscmp(progress.currentOperation, L"Post-processing video") == 0);

    // Test case 6: Destination line in post-processing
    // This should trigger ParseFileDestinationLine
    ParsePostProcessingLine(L"[ffmpeg] Destination: test_output.mp4", &progress);
    assert(wcscmp(progress.currentOperation, L"Converting video format") == 0);
    assert(progress.finalVideoFile != NULL);
    assert(wcscmp(progress.finalVideoFile, L"test_output.mp4") == 0);
    assert(progress.fileCount > 0);
    assert(wcscmp(progress.trackedFiles[0]->filePath, L"test_output.mp4") == 0);

    FreeEnhancedProgressInfo(&progress);
    printf("All ParsePostProcessingLine tests passed!\n");
}

int main() {
    test_parse_postprocessing_line();
    return 0;
}
